services:
  nextjs:
    image: puskas-2024-image
    container_name: puskas-2024-container
    build: .
    volumes:
      - .:/root/puskas-2024
      - /root/puskas-2024/node_modules
      - /root/puskas-2024/.next
    ports:
      - "3000:3000"
    tty: true
    stdin_open: true