import type { Metadata } from "next";
import { Roboto, Rock_Salt } from "next/font/google";
import "./globals.css";

const roboto = Roboto({
  weight: ["400", "900"],
  subsets: ["latin"],
  variable: "--font-roboto",
});
const rocksalt = Rock_Salt({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-rocksalt",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${roboto.variable} ${rocksalt.variable} max-sm:text-[10px] max-xl:text-[14px] text-[18px]`}
    >
      <body>{children}</body>
    </html>
  );
}
